<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("О компании");
?> <?$APPLICATION->IncludeComponent(
                    "bitrix:breadcrumb", 
                    "main", 
                    array(
                        "START_FROM" => "0",
                        "PATH" => "",
                        "SITE_ID" => "s1",
                        "COMPONENT_TEMPLATE" => "main"
                    ),
                    false
                );?> 

<?$APPLICATION->IncludeComponent(
	"bitrix:news.detail", 
	"about", 
	array(
		"COMPONENT_TEMPLATE" => "about",
		"IBLOCK_TYPE" => "about",
		"IBLOCK_ID" => "3",
		"ELEMENT_ID" => "6",
		"ELEMENT_CODE" => "",
		"CHECK_DATES" => "Y",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "show_serv",
			1 => "serv_title",
			2 => "serv_text",
			3 => "serv_link",
			4 => "serv_blank",
			5 => "show_docs",
			6 => "docs_captions",
			7 => "docs_title",
			8 => "rekv_title",
			9 => "show_rekv",
			10 => "rekv_par",
			11 => "rekv_vals",
			12 => "rekv_addr",
			13 => "rekv_phone",
			14 => "rekv_phone_link",
			15 => "rekv_show_but",
			16 => "rev_link",
			17 => "rev_blank",
			18 => "rev_link_text",
			19 => "show_reviews",
			20 => "rev_title",
			21 => "show_link",
			22 => "show_bot_form",
			23 => "service",
			24 => "docs_small",
			25 => "docs_big",
			26 => "rekv_logo",
			27 => "reviews",
			28 => "",
		),
		"IBLOCK_URL" => "",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"SET_TITLE" => "Y",
		"SET_CANONICAL_URL" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"BROWSER_TITLE" => "title",
		"SET_META_KEYWORDS" => "Y",
		"META_KEYWORDS" => "key",
		"SET_META_DESCRIPTION" => "Y",
		"META_DESCRIPTION" => "desk",
		"SET_LAST_MODIFIED" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_ELEMENT_CHAIN" => "N",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"USE_PERMISSIONS" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Страница",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"FILE_404" => ""
	),
	false
);?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>